version: '3.8'
services:
  trader:
    image: node:18
    container_name: tradingview-trader
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm start"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
